// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace BookStore.Entities.UserIdentityEntities
{
    public partial class AspNetRoleClaim
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }

        public virtual AspNetRole Role { get; set; }
    }
}