// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace BookStore.Entities.UserIdentityEntities
{
    public partial class AspNetUserRole
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }

        public virtual AspNetRole Role { get; set; }
        public virtual AspNetUser User { get; set; }
    }
}