// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace BookStore.Entities.UserIdentityEntities
{
    public partial class AspNetUserToken
    {
        public string UserId { get; set; }
        public string LoginProvider { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }

        public virtual AspNetUser User { get; set; }
    }
}