// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace BookStore.Entities.UserIdentityEntities
{
    public partial class AspNetUserLogin
    {
        public string LoginProvider { get; set; }
        public string ProviderKey { get; set; }
        public string ProviderDisplayName { get; set; }
        public string UserId { get; set; }

        public virtual AspNetUser User { get; set; }
    }
}