// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace BookStore.Entities.UserIdentityEntities
{
    public partial class AspNetUserClaim
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }

        public virtual AspNetUser User { get; set; }
    }
}