// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BookStore.Entities.UserIdentityEntities;

#nullable disable

namespace BookStore.Entities.BookStoreEntities
{
    public partial class UserFavBook
    {
        public int Id { get; set; }
        public string AspNetUserId { get; set; }
        public int BookId { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Book Book { get; set; }
    }
}