// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>


namespace BookStore.Entities.BookStoreEntities
{
    public partial class UsersTable
    {
        public int Id { get; set; }
        public string NameSurname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}