// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using BookStore.Entities.UserIdentityEntities;

namespace BookStore.Entities.BookStoreEntities
{
    public partial class UserBook
    {
        public string UserId { get; set; }
        public int BookId { get; set; }

        public virtual Book Book { get; set; }
        public virtual AspNetUser User { get; set; }
    }
}